# Setup
title:        Powerlean -通用博客
tagline:      第二存储分发库
baseurl:      ""
paginate:     1
locale:       "zh-CN"

# About/contact
author:     Powerlen
name:       Powerlen
url:        http://powerlean.top 

# Gems
gems:
  - jekyll-paginate

#Others
auto: true
markdown: kramdown
