# Setup
title:        Powerlean
tagline:      资源分享站
baseurl:      ""
paginate:     1
locale:       "zh_CN"

# About/contact
author:       Powerlean.top
  name:       Powerlean
  url:        http://powerlean.top

# Gems
gems:
  - Personal Web

#Others
markdown: kramdown
