# Setup
title: Powerlean
tagline: 主页
baseurl: ""
paginate: 1
locale: "zh-CN"

# About/contact
author: Powerlen
name: Powerlen
url: https://powerlean.top 

# Gems
gems:
  - jekyll-paginate

#Others
auto: true
markdown: kramdown
email: bluebreeze191@gmail.com
