# Site settings 配置站点
title: 'Powerlean'
description: '记录收获，解决问题'
keywords: 'linux, tech'
url: 'https://powerlean.top' # your host
baseurl: '/'

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags'
  足迹: '/timeline'
  关于: '/about'
  链接: '/friendLink'
  存储: '/blob'
  版权: '/copyright'
  登记: 'https://space.powerlean.top'
  ITFORWEB: 'https://pioi.me'
  
# 博主
author: true
name: 'Powerlean'
NickName: 'Powerlean'
webtitle: 'Powerlean'
bio: ''
about: true
aboutyou: 'A boring guy...'
portraits: '/images/favicon.ico' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Twitter', 'instagram', 'weixin']
  mail: 'mailto:powerlean@powerlean.top'
  weixin: '/503' # 你的微信二维码存放的地址
  qq: '/QQ' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yesa
  github: 'https://github.com/edges5352'
  Facebook: '/503'
  Google: '/503'

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  ITFORWEB: 'https://blog.itforweb.cn'
  PowerCollector: '/poco'
  jekyll: 'https://www.jekyll.com.cn/'
  Termux菜鸟之家: 'https://qm.qq.com/cgi-bin/qm/qr?k=T-77j4AcllqmoN7Eh5hTrPhgVwTLNZPV&authKey=Mwd5f5A07bYao3X9rI26EBN2lRXYbuYP9d+1mA57ftuLsV3sLVBPSmQhaUR4DxJK&noverify=0'
  HackError: 'https://hackerror.top'
  狗屁不通文章生成器: '/狗屁不通'
  Pacman: '/pacman'
# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
